export const greetings = [
  'Hello, darling! So happy to meet you!',
  "Hey there, beautiful! It's great to see you!",
  'Hi, love! How’s everything going?',
  'Well, hello, sunshine! So nice to see you!',
  "Hey, you! It's been way too long!",
  'Hi, sweetie! How have you been?',
  'Howdy, my friend! Always a pleasure!',
  'Hey there, gorgeous! How’s life treating you?',
  'Hello, lovely! It’s been a while!',
  'Hi, darling! So glad to see you!',
  'Well, if it isn’t my favorite person! How’s it going?',
  'Hey, beautiful! Hope everything’s going great!',
  'Hi, sweetheart! So good to catch up with you!',
  'Howdy, my dear! I’m so happy to see you!',
  'Hey there, cutie! How are you doing today?',
  'Hi, lovebug! It’s been way too long!',
  'Hello, gorgeous! How’s the day treating you?',
  'Hey, lovely! I’ve missed you!',
  'Well, look who it is! So happy to see you!',
  'Hi, darling! You look amazing as always!',
  'Hey there, star! Always a pleasure!',
  'Howdy, sweetheart! I’ve been thinking about you!',
  'Hey, beautiful soul! It’s a pleasure to see you!',
  'Hi, angel! I’m so glad we’re catching up!',
  'Hello, my favorite person!',
  'Hey, love! So nice to meet you again!',
  'Hi, you amazing human! So happy to meet you!',
  'Howdy, beautiful! I’ve been looking forward to this!',
  'Hey, sweet thing! It’s a pleasure to see you!',
  'Hi, darling! It’s so nice to see you again!',
  'Hello, love! It’s been too long!',
  'Hey, lovely! You’re looking fantastic today!',
  'Hi, gorgeous! So happy to see your face!',
  'Howdy, beautiful! I hope your day is as wonderful as you are!',
  'Hey, you! Always a joy to see you!',
  'Hi, sunshine! You light up my day!',
  'Hey, hey! So happy to meet you!',
  'Hey, sweetie pie! It’s a pleasure to see you!',
  'Hi, love! So happy we’re connecting today!',
  'Hey, hey, charming person! It’s great to be with you!',
  'Hey, pretty! How’s everything in your world?',
  'Hi, my dear! I hope you’re doing well!',
  'Hello, darling! It’s a pleasure to see you!',
  'Hey, cutie pie! How’s life treating you?',
  'Hi, gorgeous soul! What’s new with you?',
  'Hey, hey, lovely! I’ve been waiting to see you!',
  'Hey, sunshine! So happy to meet you!',
  'Hi, angel! So good to meet you again!',
  'Hello, darling! It feels great to catch up with you!',
  'Hey, sweet friend! You’re looking fabulous as always!',
  'Hi, beautiful! So glad you’re here!',
  'Hello, my love! It’s a pleasure to see you!',
  'Hey there, gorgeous! You’re radiating today!',
  'Hi, lovely! It’s wonderful to see you!',
  'Hey, hey, dear! You’re a bright spot in my day!',
  'Hey, amazing person! So happy to be with you!',
  'Hi, cutie! I’m thrilled to see you!',
  'Hello, precious! It’s a joy to meet you!',
  'Hey, lovely human! You brighten up the place!',
  'Hi, sweet soul! I’m excited to catch up with you!',
  'Hello, my favorite! Always a pleasure to see you!',
  'Hey, wonderful one! So great to see you again!',
  'Hi, sunshine! You make everything better!',
  'Hello, gorgeous! You just made my day!',
  'Hey, sweetie! I’m so happy to be here with you!',
  'Hi, darling! I’m so glad we’re together!',
  'Hello, my friend! It’s such a delight to see you!',
  'Hey, charming one! You’ve got the best energy!',
  'Hi, beautiful soul! You’re radiating good vibes!',
  'Hello, love! It’s fantastic to catch up!',
  'Hey, you! Your smile just brightened my day!',
  'Hi, sweet one! I’m so happy to be with you!',
  'Hello, my dear friend! So good to be around you!',
  'Hey, you gorgeous creature! I’m so happy to meet you!',
  'Hi, amazing human! Your presence is a gift!',
  'Hello, sweet thing! It’s such a pleasure to see you!',
  'Hey, lovely! You make life a little brighter!',
  'Hi, darling! I’ve been looking forward to this moment!',
  'Hello, sweetheart! You’re a ray of sunshine!',
  'Hey, fabulous one! You light up the room!',
  'Hi, gorgeous! It’s always a joy to meet you!',
  'Hello, my lovely! You bring so much happiness!',
  'Hey, dear one! You’ve got such a beautiful energy!',
  'Hi, precious one! So glad to see your beautiful face!',
  'Hello, sunshine! You make everything better!',
  'Hey, my darling! You’re always a breath of fresh air!',
  'Hi, amazing soul! Your energy is contagious!',
  'Hello, lovely! You’re such a wonderful person!',
  'Hey, beautiful! You always make my day!',
  'Hi, sweet friend! It’s a joy to be in your company!',
  'Hello, my star! You shine so brightly!',
  'Hey, cutie! So great to be around you!',
  'Hi, love! You’re always a delight to be with!',
  'Hello, amazing! You’re a bright spot in my day!',
  'Hey, sunshine! You’re glowing as always!',
  'Hi, beautiful! You just made my whole day!',
  'Hello, gorgeous! So happy to see you again!',
  'Hey, sweet heart! You’ve got such a great energy!',
  'Hi, darling! Your presence makes everything better!',
  'Hello, my treasure! So glad to be with you!',
  'Hey, lovely! Your spirit is uplifting!',
  'Hi, gorgeous! You light up the whole room!',
  'Hello, beautiful! You’ve made my day brighter!',
  'Hey, lovebug! Always a pleasure to see you!',
  'Hi, sweet one! You’re a joy to be around!',
];

export const factIntros = [
  'Did you know...',
  'Amazing fact...',
  "Here's a fun fact...",
  'Did you ever wonder...',
  'Fun trivia for you...',
  'Here’s something interesting...',
  'Guess what...',
  'You might be surprised...',
  'Did you realize...',
  'Here’s something cool...',
  'Believe it or not...',
  'You won’t believe this...',
  'Here’s a surprising fact...',
  'Check this out...',
  'You may not know this, but...',
  'Here’s an interesting tidbit...',
  'Have you ever heard that...',
  'It’s pretty amazing...',
  'You’ll never guess...',
  'It’s fascinating to think...',
  'Let me tell you something...',
  'Did you ever hear about...',
  'Here’s something you probably didn’t know...',
  'Imagine this...',
  'Here’s something interesting...',
  'Have you ever wondered about...',
  'Here’s an unexpected fact...',
  'I bet you didn’t know...',
  'This might blow your mind...',
  'It’s incredible that...',
  'Check out this mind-blowing fact...',
  'Did you ever come across the fact that...',
  'Ever heard the story about...',
  'It’s surprising, but...',
  "Here's something that'll surprise you...",
  'Did you know that some people think...',
  'Here’s a curious fact...',
  'Did you know the truth about...',
  'Wait until you hear this...',
  'This is something really cool...',
  'Here’s a quirky fact...',
  'Did you know the weirdest thing is...',
  'Did you know something crazy about...',
  'You might be amazed to learn...',
  'Check out this unusual fact...',
  'Here’s something you don’t hear every day...',
  'Have you ever come across the fact that...',
  'Here’s something that’ll make you think...',
  'This is an odd, but true fact...',
  'Wait, this is wild...',
];

export const facts = [
  'Australia is wider than the moon',
  'The most popular first names are Maria and Muhammad',
  'The script for "The Terminator" was sold for just $1',
  'Venus is the only planet that spins clockwise',
  'Japan has one vending machine for every 40 people',
  'Google Images was created after J. Lopez wore a green dress at the 2000 Grammys',
  'If you keep a goldfish in a dark room, it will eventually turn white',
  'People once consumed arsenic to improve their skin',
  "Over 1,400 visual effects artists needed 16 weeks to create Avengers: Endgame's final battle",
  'Sudan has more pyramids than any other country',
  "There is a McDonald's on every continent except Antarctica",
  'The Eiffel Tower was originally intended for Barcelona',
  'Lemons float, but limes sink',
  'The circulatory system is over 60,000 miles long',
  'The first-ever movie was a silent film "Roundhay Garden Scene" lasting 11 seconds',
  'Boanthropy is the psychological disorder in which patients believe they are cows',
  'Banks have therapists known as "wealth psychologists" for clients unable to cope with their wealth',
  'The real name for a hashtag is octothorpe',
  'It would take 19 minutes to fall to the center of the Earth',
  'The Pope cannot be an organ donor',
  'The "Titanic" sinking scene was filmed using a full-scale replica of the ship',
  'Sunsets on Mars are blue',
  'There are more than 3.5 million ATMs all over the world',
  'The longest English word has 189,819 letters',
  'Mosquitoes are attracted to people who just ate bananas',
  'Frida Kahlo painted 55 self-portraits',
  'The character of Darth Vader was originally meant to be a sympathetic figure',
  'The average raindrop falls at 11 kmph',
  "40% of McDonald's profits come from the sales of Happy Meals",
  'All mammals experience goosebumps',
  'The world’s termites outweigh the world’s humans about 10 to 1',
  'Identical twins don’t have the same fingerprints',
  'The "Friends" series was filmed in front of a live studio audience',
  'Smelling apples or bananas can help you lose weight',
  'Uber started as a luxury car service',
  'Cats can make more than 100 vocalizations',
  'Bullfrogs do not sleep',
  'The inventor of the frisbee was turned into a frisbee after he died',
  'The iconic "Psycho" shower scene was filmed in black and white to hide the blood effects',
  "The world's oldest wooden wheel is over 5,000 years old",
  "The first credit card was introduced in 1950 by Diner's Club",
  'The Hawaiian alphabet only has 12 letters',
  'A snail breathes through its foot',
  'The average adult human body has 206 bones, while babies have about 300',
  'The "Simpsons" series was almost canceled after season 1 because of low ratings',
  "The universe's average color is called 'cosmic latte'",
  'Netflix started as a DVD rental service',
  'Sliced bread was invented a year after the invention of TV',
  'An ant’s sense of smell is stronger than a dog’s',
  'Humans have a "diving reflex" that slows some bodily functions in water to prevent drowning',
  '"Star Wars: The Force Awakens" holds the record with an official net budget of $447 million',
  'Your brain is constantly eating itself through a process called phagocytosis',
  'Amazon began as an online bookstore',
  'It took the creator of the Rubik’s Cube one month to solve the cube after he created it',
  'Lizards communicate by doing push-ups',
  'Popcorn was invented by the Aztec Indians',
  "Jeff Bezos' dad was a circus performer before Amazon",
  'Earth’s rotation is slowing down, increasing the length of a day by about 18 sec per century',
  "Google's original name was BackRub",
  'Dogs have been banned from Antarctica since April 1994',
  'A giant squid has eyes the size of a volleyball',
  'The electric chair was invented by a dentist',
  'The voice of Mickey Mouse and the voice of Minnie Mouse were married in real life',
  'A cloud can weigh over a million tons but floats thanks to denser air below',
  'The first social media platform, SixDegrees, was launched in 1999',
  'The average person walks the equivalent of five times around the world in their lifetime',
  "Elephants are the only mammals that can't jump",
  'The average person takes about 23,000 breaths a day',
  'The first animated feature film was Disney\'s "Snow White and the Seven Dwarfs"',
  'Water can boil and freeze at the same time',
  'Most mobile banner clicks are accidental due to "fat-finger taps"',
  'Bananas are berries, but strawberries are not',
  'Mosquitoes have 47 teeth',
  'Indonesia is home to some of the shortest people in the world',
  'The iconic scream in horror films is known as the "Wilhelm scream"',
  'Light from the Sun takes about 8 minutes to reach Earth',
  "Coca-Cola's logo is recognized by 94% of the global population",
  'The shortest war in history lasted only 38 minutes',
  'Tigers have striped skin, not just striped fur',
  'The average person laughs 15-20 times a day',
  '"Friends" was originally titled "Insomnia Cafe"',
  "Allodoxaphobia is the fear of other people's opinions",
  'FedEx almost went bankrupt. The founder gambled to save it',
  'Banana plants are herbs, not trees',
  'Dogs sniff good smells with their left nostril',
  'The average person spends about 10 years of their life sleeping',
  "In Japan, there's a theme park dedicated entirely to cats",
  'A lightning bolt is five times hotter than the surface of the Sun',
  'Marvel once owned the rights to the word "zombie"',
  'The scent of vanilla has been found to have a relaxing and calming effect on the mind and body',
  'The hummingbird is the only bird that can fly backward',
  'The human heart beats about 100,000 times a day',
  'The average person checks their phone 150 times daily',
  'The snow on Pluto is red',
  "Domino's co-founder traded his half for a used Volkswagen",
  'In the 1830s ketchup was often sold as a medicine',
  'Beavers were once the size of bears',
  'The average person blinks about 15-20 times a minute',
  'The character of Shrek was originally designed to be much scarier',
  'A year on Mercury is only 88 days long, but a full day as we know is about 59 days',
  'The Nike swoosh designer was paid only $35 for the logo',
  "The first product to have a barcode was Wrigley's gum",
  'Giraffes are 30 times more likely to get hit by lightning than humans',
  'The average person will walk the equivalent of five times around the Earth in their lifetime',
  'Elsa\'s castle in "Frozen" was inspired by the iconic Ice Hotel in Sweden',
  'Sir Isaac Newton was only 23 years old when he discovered the law of universal gravitation',
  "Facebook's main color is blue due to Mark Zuckerberg's color blindness",
  "The first McDonald's menu item was a hotdog, not a burger",
  "50% of the world's oxygen is produced by the sea, not rainforests",
  'Your stomach gets a new lining every few days to prevent it from digesting itself',
  'Jim Carrey once wrote himself a $10 million check for acting success',
  'Jupiter has 79 moons. 26 are still waiting to be officially named',
  'Apple became the first company worth over $700 billion in 2015',
  'Starbucks uses round tables to make customers feel less alone',
  'Octopuses have three hearts and blue blood',
  'You produce about one liter of saliva each day',
  'The first-ever music video played on MTV was "Video Killed the Radio Star"',
  'Most known asteroids in our solar system are located between Jupiter and Mars',
  'The average revenue for small businesses with no employees is around $44,000 per year',
  'Brazil got its name from the nut, not the other way around',
  'There are more trees on Earth than stars in the Milky Way galaxy',
  'The average human will shed around 20 kilograms of skin in their lifetime',
  'In the movie "Jaws" the shark was called Bruce after Spielberg\'s lawyer',
  'In 1962, a scientist named Sheila Lowe did indeed invent a bra that could double as a gas mask',
  'The first item sold on eBay was a broken laser pointer',
  'The inventor of Vaseline ate a spoonful daily for health benefits',
  'A jellyfish is 95% water',
  'A sneeze travels at about 100 miles per hour',
  "The voice of Darth Vader is James Earl Jones, but he wasn't credited initially",
  'A day on Venus is longer than a year on Venus due to its slow rotation',
  'The average office worker spends about 28% of their time in meetings',
  'In Japan, there are more pets than children under 15 years old',
  "Cows have 'best friends' and get stressed when separated",
  'Your nose can distinguish between over 1 trillion different scents',
  "Samuel L. Jackson has a lightsaber with 'Bad Motherfucker' engraved on it",
  'Chess has more possible iterations of a game than the universe has atoms',
  'Monopoly was invented to warn against monopolies',
  "Scotland's national animal is the unicorn",
  'Flamingos bend their legs at the ankle, not the knee',
  'Humans share 60% of their DNA with bananas',
  'Darth Vader only speaks for 12 minutes in the original Star Wars trilogy',
  'Bananas are radioactive due to potassium, but not dangerous',
  "Amazon started in Bezos' garage with a spray-painted sign",
  'More people die each year from vending machines than from shark attacks',
  "A blue whale's heart is the size of a small car",
  'We spend about six months of our lives, waiting at green lights',
  'The sound of a lightsaber is a mix of a film projector and a microphone feedback',
  'Arabic numerals were created in India',
  "The first McDonald's menu introduced in the 1940s had only 9 items",
  'The original purpose of Play-Doh was to clean wallpaper',
  'Sloths can hold their breath longer than dolphins',
  'Everyone has a unique tongue print, just like fingerprints',
  'The original Hulk was painted gray before switching to green',
  'A teaspoon of a neutron star would weigh about 6 billion tons',
  "Google's first storage was made from Lego bricks",
  'Honey never spoils, archaeologists found pots of it in ancient Egyptian tombs',
  'Octopuses punch fish out of spite',
  'Humans are the only animals with chins',
  '007 James Bond was inspired by a bird expert of the same name',
  'Some metals can explode when exposed to water, like sodium and potassium',
  'SpaceX once sold flamethrowers, because Musk thought it was funny',
  "A jiffy is an actual unit of time. It's one-hundredth of a second",
  'The Mississippi River once started flowing backwards after an earthquake',
  'The loudest recorded sneeze was over 170 decibels',
  'Keanu Reeves gave away most of his Matrix earnings to the crew',
  'LSD was discovered by a chemist who accidentally dosed himself',
  "In 1982 Lucy L. Barmby patented the 'Anti-eating face mask'",
  'Napoleon was once attacked by a horde of rabbits',
  'Koalas have fingerprints similar to humans',
  'Your left lung is smaller than your right lung to make room for your heart',
  'LinkedIn was launched in a living room',
  'The sun loses 4 million tons of mass per second as energy',
  "Apple's first logo showed Isaac Newton under an apple tree",
  'The king of hearts is the only king without a mustache on a standard playing card',
  'Most ginger cats are male',
  'You are taller in the morning than in the evening due to spinal compression',
  'YouTube started as a video dating site',
  'Light from the sun is 30,000 years old before reaching us',
  'Starbucks is named after a character in Moby-Dick',
  'Tomato sauce was sold as medicine in the 1830s',
  'An octopus can squeeze through any hole larger than its beak',
  "You can't hum while holding your nose shut",
  'Toy Story was the first fully computer-generated feature film',
  'A rubber band heats when stretched, cools when released',
  'Nintendo started as a playing card company in 1889',
  'The inventor of the Pringles can was buried in one',
  'Plants came before seeds',
  'People are more likely to remember the first and last items on a list',
  'LinkedIn is older than Facebook, Twitter, and Instagram',
  'Jupiter has 79 known moons',
  'Google tried to sell itself to Yahoo for $1 million in 1998',
  'A single teaspoon of honey represents the life work of 12 bees',
  'The heart of a shrimp is located in its head',
  'Your brain generates enough electricity to power a small light bulb',
  'The Simpsons is the longest-running scripted primetime series',
  'You can theoretically survive space exposure for 15 seconds',
  'Samsung began as a grocery trading company',
  'Polo is the oldest known team sport, dating back to 6th century BC Persia',
  'Lobsters pee from their faces',
  'Goosebumps are vestigial reflexes from our hairy ancestors',
  'Instagram was made in just 8 weeks',
  'The Milky Way has a giant black hole at its center',
  'J.K. Rowling wrote the first Harry Potter book on a train ride to London',
  'Pablo Picasso could draw before he could walk',
  'Butterflies taste with their feet',
  'Your skin renews itself every 28 days',
  "In The Matrix Neo's passport expires on September 11, 2001",
  'Sound travels faster in water than in air, even faster in steel',
  "Apple's iPhone almost went by the name 'Mobi'",
  "Antarctica holds 60% of Earth's fresh water",
  'The Mantis shrimp can punch with the force of a bullet',
  'The strongest muscle in the human body is the jaw muscle',
  'The first YouTube video is of a guy at the zoo',
  'A neutron star spins up to 600 times per second',
  'Nintendo once made instant rice',
  '40 tons of cosmic dust fall on Earth every day',
  'Penguins propose to each other by giving their mates a pebble',
  'Yawning cools down your brain',
  'Alfred Hitchcock never won an Oscar for Best Director',
  "Einstein once called quantum entanglement 'spooky action'",
  'Airbnb started by renting air mattresses in an apartment',
  'NBA players once played in converse shoes',
  "A blue whale's tongue weighs as much as an elephant",
  'Fingernails grow faster than toenails',
  "Lego is from the Danish words 'Leg Godt' meaning 'play well'",
  "Earth's magnetic poles flip every 250,000 years",
  "McDonald's used to sell hot dogs",
  'Snoop Dogg was once a high school football star',
  'Sea otters hold hands while sleeping to avoid drifting apart',
  'Human bones are stronger than steel',
  'In Pulp Fiction, many of the clocks and watches show 4:20',
  "99.9% of the atom's volume is empty space",
  "Beyonce's first job was at McDonald's when she was 15",
  'Lightning strikes Earth 8.6 million times per day',
  'Some sharks glow in the dark',
  'Smiling uses fewer muscles than frowning',
  'TikTok was first known as Douyin in China',
  'Neutrinos can pass through the entire Earth undetected',
  'Ferrari once turned down a partnership with Ford',
  'Golf balls were originally made of leather and feathers',
  'Chameleons change color for communication, not just camouflage',
  'Hiccups can last for days, even years',
  'Pinterest has more female users than any other platform',
  "Earth's gravity warps time, making satellites' clocks faster",
  'A French engineer invented an inflatable car for parking in tight spaces',
  "Earth's crust is thinner than an apple's skin proportionally",
  "Elephants can 'hear' through their feet",
  'Your bones are in a constant state of renewal',
  'Leonardo DiCaprio sliced his hand for real in Django Unchained',
  'Plasma TVs hold tiny amounts of radioactive gas',
  'Sony was originally a rice cooker company',
  'Boxing was an Olympic sport in 688 BC',
  'Some frogs can freeze without dying, thawing out later',
  'Skin is the largest organ in the body',
  "Snapchat's ghost logo is called 'Ghostface Chillah'",
  'In space, flames are round due to the lack of gravity',
  'Instagram was bought by Facebook for $1 billion with just 13 employees',
  "Deserts cover about one-third of Earth's land area",
  'Bees have five eyes',
  "Humans glow in the dark, but it's too faint for us to see",
  'Charlie Chaplin lost a Chaplin lookalike contest',
  'Lasers are used to cool atoms to near absolute zero',
  "Tesla was nearly called 'Faraday'",
  "Only 5% of Earth's oceans have been explored",
  "Kangaroos can't walk backward",
  'You can survive without a stomach, spleen, or one kidney',
  'Alfred Hitchcock was afraid of eggs',
  "Earth's atmosphere leaks 90 tons of hydrogen into space daily",
  "Subway was originally named Pete's Super Submarines",
  'The Olympic Games were originally a religious festival',
  "Elephants are the only animals that can't jump",
  'Your stomach acid could dissolve a razor blade',
  'Daniel Radcliffe went through 80 wands filming Harry Potter',
  'The universe may have more dimensions than we can see',
  'Lamborghini started by making tractors',
  'Gravity is weaker at the equator than the poles',
  'Dolphins sleep with one eye open',
  'You could technically survive on a diet of potatoes and butter',
  'James Cameron drew the sketch of Rose in Titanic himself',
  'A photon can be in two places at once until observed',
  'Nike founder Phil Knight sold shoes out of his car',
  'The Atlantic Ocean grows by about 1 inch yearly',
  'Squirrels plant thousands of trees by forgetting their nuts',
  "Human's liver can regrow itself even if 75% is removed",
  "The Simpsons' couch gag can be as long as 90 seconds",
  'Venus has acid rain that never reaches the ground',
  "Google's first office was a friend's garage in Menlo Park, CA",
  'Dead Sea is the lowest land spot at 430 meters below sea level',
  "Horses can't vomit",
  'The brain can store 2.5 million gigabytes of memory',
  'Pinterest was originally called Tote',
  'You can fit all atoms of humanity in a sugar cube',
  "KFC's founder started the chain at age 65",
  'The moon moves 3.8 cm away from Earth each year',
  'Koalas sleep up to 22 hours a day',
  'Humans can smell fear and disgust in others',
  "Morgan Freeman didn't start acting seriously until he was 50",
  'Antimatter is real and can annihilate with matter on contact',
  'IBM helped create the barcodes on every product',
  "Earth's oceans contain 20 million tons of gold",
];
